#!/bin/bash

if [ -z "$1" ]; then
    echo "uso: set-wallpaper /caminho/da/imagem.jpg"
    exit 1
fi

IMAGE="$1"

qdbus org.kde.plasmashell /PlasmaShell evaluateScript "
var allDesktops = desktops();
for (i=0;i<allDesktops.length;i++) {
  d = allDesktops[i];
  d.wallpaperPlugin = 'org.kde.image';
  d.currentConfigGroup = Array('Wallpaper','org.kde.image','General');
  d.writeConfig('Image','file://$IMAGE');
}"

